name: "Download Event File"
description: "Download GitHub Event file from artifacts"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: 'Download artifact'
      id: get-artifacts
      uses: actions/github-script@v3.1.0
      with:
        script: |
          var artifacts = await github.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: ${{github.event.workflow_run.id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "verible-trigger.json"
          })[0];
          var download = await github.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: matchArtifact.id,
             archive_format: 'zip',
          });
          var fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/verible-trigger.json.zip', Buffer.from(download.data));
    - run: |
      shell: bash
        unzip verible-trigger.json.zip
        mv verible-trigger.json event.json
